[package]
name = "seqdist"
version = "0.1.0"
authors = ["igavriil <iasongavriil@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
